//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCClient.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VCClient.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted by user.
        /// </summary>
        internal static string CalculationStatus_AbortedByUser {
            get {
                return ResourceManager.GetString("CalculationStatus.AbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code not entered.
        /// </summary>
        internal static string CalculationStatus_BarcodeNotEntered {
            get {
                return ResourceManager.GetString("CalculationStatus.BarcodeNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation error.
        /// </summary>
        internal static string CalculationStatus_CalculationError {
            get {
                return ResourceManager.GetString("CalculationStatus.CalculationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CalculationStatus_ErrorPrefix {
            get {
                return ResourceManager.GetString("CalculationStatus.ErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation result file still open.
        /// </summary>
        internal static string CalculationStatus_FailedToCloseFiles {
            get {
                return ResourceManager.GetString("CalculationStatus.FailedToCloseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to select algorithm.
        /// </summary>
        internal static string CalculationStatus_FailedToSelectAlgorithm {
            get {
                return ResourceManager.GetString("CalculationStatus.FailedToSelectAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start.
        /// </summary>
        internal static string CalculationStatus_FailedToStart {
            get {
                return ResourceManager.GetString("CalculationStatus.FailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing calculation....
        /// </summary>
        internal static string CalculationStatus_InProgress {
            get {
                return ResourceManager.GetString("CalculationStatus.InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object not found.
        /// </summary>
        internal static string CalculationStatus_ObjectNotFound {
            get {
                return ResourceManager.GetString("CalculationStatus.ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autotimer running....
        /// </summary>
        internal static string CalculationStatus_Pending {
            get {
                return ResourceManager.GetString("CalculationStatus.Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to calculate.
        /// </summary>
        internal static string CalculationStatus_Ready {
            get {
                return ResourceManager.GetString("CalculationStatus.Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation complete.
        /// </summary>
        internal static string CalculationStatus_Successful {
            get {
                return ResourceManager.GetString("CalculationStatus.Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device connection error.
        /// </summary>
        internal static string CalculationStatus_TimedOut {
            get {
                return ResourceManager.GetString("CalculationStatus.TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is not stable.
        /// </summary>
        internal static string CalculationStatus_WeightNotStable {
            get {
                return ResourceManager.GetString("CalculationStatus.WeightNotStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate size.
        /// </summary>
        internal static string DashboardControl_CalculateSize {
            get {
                return ResourceManager.GetString("DashboardControl.CalculateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DashboardControl_Cancel {
            get {
                return ResourceManager.GetString("DashboardControl.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string DashboardControl_Cm {
            get {
                return ResourceManager.GetString("DashboardControl.Cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string DashboardControl_Code {
            get {
                return ResourceManager.GetString("DashboardControl.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string DashboardControl_Comment {
            get {
                return ResourceManager.GetString("DashboardControl.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string DashboardControl_Mm {
            get {
                return ResourceManager.GetString("DashboardControl.Mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open photo folder.
        /// </summary>
        internal static string DashboardControl_OpenPhotoFolder {
            get {
                return ResourceManager.GetString("DashboardControl.OpenPhotoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open result file.
        /// </summary>
        internal static string DashboardControl_OpenResultFile {
            get {
                return ResourceManager.GetString("DashboardControl.OpenResultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset scales.
        /// </summary>
        internal static string DashboardControl_ResetScales {
            get {
                return ResourceManager.GetString("DashboardControl.ResetScales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string DashboardControl_Size {
            get {
                return ResourceManager.GetString("DashboardControl.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string DashboardControl_Units {
            get {
                return ResourceManager.GetString("DashboardControl.Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string DashboardControl_Weight {
            get {
                return ResourceManager.GetString("DashboardControl.Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Toolbar_ActionsButton {
            get {
                return ResourceManager.GetString("Toolbar.ActionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display debug info.
        /// </summary>
        internal static string Toolbar_DisplayDebugInfoButton {
            get {
                return ResourceManager.GetString("Toolbar.DisplayDebugInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Configurator.
        /// </summary>
        internal static string Toolbar_OpenConfiguratorButton {
            get {
                return ResourceManager.GetString("Toolbar.OpenConfiguratorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        internal static string Toolbar_OpenSettingsButton {
            get {
                return ResourceManager.GetString("Toolbar.OpenSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save test data.
        /// </summary>
        internal static string Toolbar_SaveTestDataButton {
            get {
                return ResourceManager.GetString("Toolbar.SaveTestDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut down.
        /// </summary>
        internal static string Toolbar_ShutDownButton {
            get {
                return ResourceManager.GetString("Toolbar.ShutDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System information.
        /// </summary>
        internal static string Toolbar_SystemInformationButton {
            get {
                return ResourceManager.GetString("Toolbar.SystemInformationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Toolbar_ToolsButton {
            get {
                return ResourceManager.GetString("Toolbar.ToolsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gr.
        /// </summary>
        internal static string WeightUnits_Gr {
            get {
                return ResourceManager.GetString("WeightUnits.Gr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string WeightUnits_Kg {
            get {
                return ResourceManager.GetString("WeightUnits.Kg", resourceCulture);
            }
        }
    }
}
